### ISSUE TITLE
[BUG] Configuration ignored after `suppressed_errors =` in toml file

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/foundry-zksync#907]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

0.0.8

### What command(s) is the bug in?

forge build

### Operating System

None

### Describe the bug

If you specify a configuration like so, where `suppressed-errors` are included the rest of the config file is ignored. 

```toml
[profile.default.zksync] 
suppressed_errors = ["assemblycreate", "sendtransfer"]
zksolc = "1.5.10"
```

This will build with default zksolc 1.5.11 ignoring the specified version. However, if you switch the ordering between `suppressed_errors` and `zksolc` you correctly use 1.5.10.
